
project_id = "xhccvoivnelbzvzxmcoy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[realtime]
enabled = true

[analytics]
enabled = true
port = 54327

[vector]
enabled = true
port = 54328

[functions]
enabled = true
port = 54326

[functions.update-user-schedule-settings]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.linkedin-oauth]
verify_jwt = true

[functions.post-to-linkedin]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.generate-content-from-image]
verify_jwt = true

[functions.post-to-linkedin-direct]
verify_jwt = true

[functions.facebook-oauth]
verify_jwt = true

[functions.instagram-oauth]
verify_jwt = true

[functions.post-to-facebook]
verify_jwt = true

[functions.post-to-instagram]
verify_jwt = true

[functions.post-to-facebook-direct]
verify_jwt = true

[functions.post-to-instagram-direct]
verify_jwt = true

[functions.validate-recaptcha]
verify_jwt = false

[functions.get-linkedin-auth-url]
verify_jwt = false

[functions.get-facebook-auth-url]
verify_jwt = false

[functions.get-instagram-auth-url]
verify_jwt = false

[functions.linkedin-oauth-simple]
verify_jwt = false

[functions.facebook-oauth-simple]
verify_jwt = false

[functions.instagram-oauth-simple]
verify_jwt = false
